// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1.Data;

namespace WebApp1.Migrations
{
    [DbContext(typeof(ModelsDbContext))]
    [Migration("20210405143308_ModelsMigration")]
    partial class ModelsMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AgenziaFotografica.Model.Books", b =>
                {
                    b.Property<string>("pkBook")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataBook")
                        .HasColumnType("TEXT");

                    b.Property<string>("descrizioneBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fkCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("fkModello")
                        .HasColumnType("TEXT");

                    b.Property<int>("numeroScatti")
                        .HasColumnType("INTEGER");

                    b.HasKey("pkBook");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AgenziaFotografica.Model.Clienti", b =>
                {
                    b.Property<string>("pkCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazioneCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RagioneSocialeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("emailCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkCliente");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("AgenziaFotografica.Model.Modelli", b =>
                {
                    b.Property<string>("pkModello")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("TEXT");

                    b.Property<string>("NazioneModello")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeModello")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("emailModello")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("pkModello");

                    b.ToTable("Modelli");
                });
#pragma warning restore 612, 618
        }
    }
}
